/*
 * Pay with Rewards APIs
 *
 * Pay with Rewards allows cardholders to redeem points for purchases made with an enrolled Mastercard card. The following APIs create the Pay with Rewards user experience, and can be used inside a banking app or other mobile apps.
 *
 * The version of the OpenAPI document: 1.1
 * Contact: paywithrewards@mastercard.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Pbo.App.MastercardApi.Client.Api;
using Pbo.App.MastercardApi.Client.Model;
using Pbo.App.MastercardApi.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Pbo.App.MastercardApi.Client.Test.Model
{
    /// <summary>
    ///  Class for testing Account
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AccountTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Account
        //private Account instance;

        public AccountTests()
        {
            // TODO uncomment below to create an instance of Account
            //instance = new Account();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Account
        /// </summary>
        [Fact]
        public void AccountInstanceTest()
        {
            // TODO uncomment below to test "IsType" Account
            //Assert.IsType<Account>(instance);
        }


        /// <summary>
        /// Test the property 'AccountId'
        /// </summary>
        [Fact]
        public void AccountIdTest()
        {
            // TODO unit test for the property 'AccountId'
        }
        /// <summary>
        /// Test the property 'AccountIdType'
        /// </summary>
        [Fact]
        public void AccountIdTypeTest()
        {
            // TODO unit test for the property 'AccountIdType'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'ProductCode'
        /// </summary>
        [Fact]
        public void ProductCodeTest()
        {
            // TODO unit test for the property 'ProductCode'
        }
        /// <summary>
        /// Test the property 'ProgramIdentifier'
        /// </summary>
        [Fact]
        public void ProgramIdentifierTest()
        {
            // TODO unit test for the property 'ProgramIdentifier'
        }
        /// <summary>
        /// Test the property 'OpenDate'
        /// </summary>
        [Fact]
        public void OpenDateTest()
        {
            // TODO unit test for the property 'OpenDate'
        }
        /// <summary>
        /// Test the property 'EnrollmentDate'
        /// </summary>
        [Fact]
        public void EnrollmentDateTest()
        {
            // TODO unit test for the property 'EnrollmentDate'
        }
        /// <summary>
        /// Test the property 'AccruePoints'
        /// </summary>
        [Fact]
        public void AccruePointsTest()
        {
            // TODO unit test for the property 'AccruePoints'
        }
        /// <summary>
        /// Test the property 'HouseholdToken'
        /// </summary>
        [Fact]
        public void HouseholdTokenTest()
        {
            // TODO unit test for the property 'HouseholdToken'
        }
        /// <summary>
        /// Test the property 'PrimaryAccount'
        /// </summary>
        [Fact]
        public void PrimaryAccountTest()
        {
            // TODO unit test for the property 'PrimaryAccount'
        }
        /// <summary>
        /// Test the property 'CompanyIca'
        /// </summary>
        [Fact]
        public void CompanyIcaTest()
        {
            // TODO unit test for the property 'CompanyIca'
        }
        /// <summary>
        /// Test the property 'AccountFirstFour'
        /// </summary>
        [Fact]
        public void AccountFirstFourTest()
        {
            // TODO unit test for the property 'AccountFirstFour'
        }
        /// <summary>
        /// Test the property 'AccountLastFour'
        /// </summary>
        [Fact]
        public void AccountLastFourTest()
        {
            // TODO unit test for the property 'AccountLastFour'
        }
        /// <summary>
        /// Test the property 'PcloAccountStatusCode'
        /// </summary>
        [Fact]
        public void PcloAccountStatusCodeTest()
        {
            // TODO unit test for the property 'PcloAccountStatusCode'
        }
        /// <summary>
        /// Test the property 'UserDefined1'
        /// </summary>
        [Fact]
        public void UserDefined1Test()
        {
            // TODO unit test for the property 'UserDefined1'
        }
        /// <summary>
        /// Test the property 'UserDefined2'
        /// </summary>
        [Fact]
        public void UserDefined2Test()
        {
            // TODO unit test for the property 'UserDefined2'
        }
        /// <summary>
        /// Test the property 'UserDefined3'
        /// </summary>
        [Fact]
        public void UserDefined3Test()
        {
            // TODO unit test for the property 'UserDefined3'
        }
        /// <summary>
        /// Test the property 'UserDefined4'
        /// </summary>
        [Fact]
        public void UserDefined4Test()
        {
            // TODO unit test for the property 'UserDefined4'
        }
        /// <summary>
        /// Test the property 'UserDefined5'
        /// </summary>
        [Fact]
        public void UserDefined5Test()
        {
            // TODO unit test for the property 'UserDefined5'
        }
        /// <summary>
        /// Test the property 'UserDefined6'
        /// </summary>
        [Fact]
        public void UserDefined6Test()
        {
            // TODO unit test for the property 'UserDefined6'
        }
        /// <summary>
        /// Test the property 'UserDefined7'
        /// </summary>
        [Fact]
        public void UserDefined7Test()
        {
            // TODO unit test for the property 'UserDefined7'
        }
        /// <summary>
        /// Test the property 'UserDefined8'
        /// </summary>
        [Fact]
        public void UserDefined8Test()
        {
            // TODO unit test for the property 'UserDefined8'
        }

    }

}
