/*
 * Pay with Rewards APIs
 *
 * Pay with Rewards allows cardholders to redeem points for purchases made with an enrolled Mastercard card. The following APIs create the Pay with Rewards user experience, and can be used inside a banking app or other mobile apps.
 *
 * The version of the OpenAPI document: 1.1
 * Contact: paywithrewards@mastercard.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Pbo.App.MastercardApi.Client.Api;
using Pbo.App.MastercardApi.Client.Model;
using Pbo.App.MastercardApi.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Pbo.App.MastercardApi.Client.Test.Model
{
    /// <summary>
    ///  Class for testing ConversionRuleTier
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ConversionRuleTierTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ConversionRuleTier
        //private ConversionRuleTier instance;

        public ConversionRuleTierTests()
        {
            // TODO uncomment below to create an instance of ConversionRuleTier
            //instance = new ConversionRuleTier();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ConversionRuleTier
        /// </summary>
        [Fact]
        public void ConversionRuleTierInstanceTest()
        {
            // TODO uncomment below to test "IsType" ConversionRuleTier
            //Assert.IsType<ConversionRuleTier>(instance);
        }


        /// <summary>
        /// Test the property 'FromAmount'
        /// </summary>
        [Fact]
        public void FromAmountTest()
        {
            // TODO unit test for the property 'FromAmount'
        }
        /// <summary>
        /// Test the property 'ToAmount'
        /// </summary>
        [Fact]
        public void ToAmountTest()
        {
            // TODO unit test for the property 'ToAmount'
        }
        /// <summary>
        /// Test the property 'Multiplier'
        /// </summary>
        [Fact]
        public void MultiplierTest()
        {
            // TODO unit test for the property 'Multiplier'
        }
        /// <summary>
        /// Test the property 'TierNumber'
        /// </summary>
        [Fact]
        public void TierNumberTest()
        {
            // TODO unit test for the property 'TierNumber'
        }

    }

}
