/*
 * Pay with Rewards APIs
 *
 * Pay with Rewards allows cardholders to redeem points for purchases made with an enrolled Mastercard card. The following APIs create the Pay with Rewards user experience, and can be used inside a banking app or other mobile apps.
 *
 * The version of the OpenAPI document: 1.1
 * Contact: paywithrewards@mastercard.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Pbo.App.MastercardApi.Client.Api;
using Pbo.App.MastercardApi.Client.Model;
using Pbo.App.MastercardApi.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Pbo.App.MastercardApi.Client.Test.Model
{
    /// <summary>
    ///  Class for testing HouseholdInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class HouseholdInfoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for HouseholdInfo
        //private HouseholdInfo instance;

        public HouseholdInfoTests()
        {
            // TODO uncomment below to create an instance of HouseholdInfo
            //instance = new HouseholdInfo();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of HouseholdInfo
        /// </summary>
        [Fact]
        public void HouseholdInfoInstanceTest()
        {
            // TODO uncomment below to test "IsType" HouseholdInfo
            //Assert.IsType<HouseholdInfo>(instance);
        }


        /// <summary>
        /// Test the property 'PointBalance'
        /// </summary>
        [Fact]
        public void PointBalanceTest()
        {
            // TODO unit test for the property 'PointBalance'
        }
        /// <summary>
        /// Test the property 'HouseholdRole'
        /// </summary>
        [Fact]
        public void HouseholdRoleTest()
        {
            // TODO unit test for the property 'HouseholdRole'
        }

    }

}
