/*
 * Pay with Rewards APIs
 *
 * Pay with Rewards allows cardholders to redeem points for purchases made with an enrolled Mastercard card. The following APIs create the Pay with Rewards user experience, and can be used inside a banking app or other mobile apps.
 *
 * The version of the OpenAPI document: 1.1
 * Contact: paywithrewards@mastercard.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Pbo.App.MastercardApi.Client.Api;
using Pbo.App.MastercardApi.Client.Model;
using Pbo.App.MastercardApi.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Pbo.App.MastercardApi.Client.Test.Model
{
    /// <summary>
    ///  Class for testing RedemptionRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RedemptionRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RedemptionRequest
        //private RedemptionRequest instance;

        public RedemptionRequestTests()
        {
            // TODO uncomment below to create an instance of RedemptionRequest
            //instance = new RedemptionRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RedemptionRequest
        /// </summary>
        [Fact]
        public void RedemptionRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" RedemptionRequest
            //Assert.IsType<RedemptionRequest>(instance);
        }


        /// <summary>
        /// Test the property 'CashBackAmount'
        /// </summary>
        [Fact]
        public void CashBackAmountTest()
        {
            // TODO unit test for the property 'CashBackAmount'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'ExternalId'
        /// </summary>
        [Fact]
        public void ExternalIdTest()
        {
            // TODO unit test for the property 'ExternalId'
        }
        /// <summary>
        /// Test the property 'PaymentAuthId'
        /// </summary>
        [Fact]
        public void PaymentAuthIdTest()
        {
            // TODO unit test for the property 'PaymentAuthId'
        }
        /// <summary>
        /// Test the property 'PointsRedeemed'
        /// </summary>
        [Fact]
        public void PointsRedeemedTest()
        {
            // TODO unit test for the property 'PointsRedeemed'
        }
        /// <summary>
        /// Test the property 'ReasonCode'
        /// </summary>
        [Fact]
        public void ReasonCodeTest()
        {
            // TODO unit test for the property 'ReasonCode'
        }
        /// <summary>
        /// Test the property 'RedemptionType'
        /// </summary>
        [Fact]
        public void RedemptionTypeTest()
        {
            // TODO unit test for the property 'RedemptionType'
        }
        /// <summary>
        /// Test the property 'UserId'
        /// </summary>
        [Fact]
        public void UserIdTest()
        {
            // TODO unit test for the property 'UserId'
        }
        /// <summary>
        /// Test the property 'UserIdType'
        /// </summary>
        [Fact]
        public void UserIdTypeTest()
        {
            // TODO unit test for the property 'UserIdType'
        }

    }

}
