/*
 * Pay with Rewards APIs
 *
 * Pay with Rewards allows cardholders to redeem points for purchases made with an enrolled Mastercard card. The following APIs create the Pay with Rewards user experience, and can be used inside a banking app or other mobile apps.
 *
 * The version of the OpenAPI document: 1.1
 * Contact: paywithrewards@mastercard.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Pbo.App.MastercardApi.Client.Api;
using Pbo.App.MastercardApi.Client.Model;
using Pbo.App.MastercardApi.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Pbo.App.MastercardApi.Client.Test.Model
{
    /// <summary>
    ///  Class for testing SearchProfileRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SearchProfileRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SearchProfileRequest
        //private SearchProfileRequest instance;

        public SearchProfileRequestTests()
        {
            // TODO uncomment below to create an instance of SearchProfileRequest
            //instance = new SearchProfileRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SearchProfileRequest
        /// </summary>
        [Fact]
        public void SearchProfileRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" SearchProfileRequest
            //Assert.IsType<SearchProfileRequest>(instance);
        }


        /// <summary>
        /// Test the property 'UserId'
        /// </summary>
        [Fact]
        public void UserIdTest()
        {
            // TODO unit test for the property 'UserId'
        }
        /// <summary>
        /// Test the property 'UserIdType'
        /// </summary>
        [Fact]
        public void UserIdTypeTest()
        {
            // TODO unit test for the property 'UserIdType'
        }
        /// <summary>
        /// Test the property 'RedemptionType'
        /// </summary>
        [Fact]
        public void RedemptionTypeTest()
        {
            // TODO unit test for the property 'RedemptionType'
        }

    }

}
