/*
 * Pay with Rewards APIs
 *
 * Pay with Rewards allows cardholders to redeem points for purchases made with an enrolled Mastercard card. The following APIs create the Pay with Rewards user experience, and can be used inside a banking app or other mobile apps.
 *
 * The version of the OpenAPI document: 1.1
 * Contact: paywithrewards@mastercard.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Pbo.App.MastercardApi.Client.Api;
using Pbo.App.MastercardApi.Client.Model;
using Pbo.App.MastercardApi.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Pbo.App.MastercardApi.Client.Test.Model
{
    /// <summary>
    ///  Class for testing UserUpdateRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UserUpdateRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UserUpdateRequest
        //private UserUpdateRequest instance;

        public UserUpdateRequestTests()
        {
            // TODO uncomment below to create an instance of UserUpdateRequest
            //instance = new UserUpdateRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UserUpdateRequest
        /// </summary>
        [Fact]
        public void UserUpdateRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" UserUpdateRequest
            //Assert.IsType<UserUpdateRequest>(instance);
        }


        /// <summary>
        /// Test the property 'Address'
        /// </summary>
        [Fact]
        public void AddressTest()
        {
            // TODO unit test for the property 'Address'
        }
        /// <summary>
        /// Test the property 'PcloUser'
        /// </summary>
        [Fact]
        public void PcloUserTest()
        {
            // TODO unit test for the property 'PcloUser'
        }
        /// <summary>
        /// Test the property 'BirthDate'
        /// </summary>
        [Fact]
        public void BirthDateTest()
        {
            // TODO unit test for the property 'BirthDate'
        }
        /// <summary>
        /// Test the property 'BusinessPhoneNumber'
        /// </summary>
        [Fact]
        public void BusinessPhoneNumberTest()
        {
            // TODO unit test for the property 'BusinessPhoneNumber'
        }
        /// <summary>
        /// Test the property 'EmailAddress'
        /// </summary>
        [Fact]
        public void EmailAddressTest()
        {
            // TODO unit test for the property 'EmailAddress'
        }
        /// <summary>
        /// Test the property 'Employee'
        /// </summary>
        [Fact]
        public void EmployeeTest()
        {
            // TODO unit test for the property 'Employee'
        }
        /// <summary>
        /// Test the property 'FirstName'
        /// </summary>
        [Fact]
        public void FirstNameTest()
        {
            // TODO unit test for the property 'FirstName'
        }
        /// <summary>
        /// Test the property 'GenericIdentification'
        /// </summary>
        [Fact]
        public void GenericIdentificationTest()
        {
            // TODO unit test for the property 'GenericIdentification'
        }
        /// <summary>
        /// Test the property 'GenericIdentificationDescription'
        /// </summary>
        [Fact]
        public void GenericIdentificationDescriptionTest()
        {
            // TODO unit test for the property 'GenericIdentificationDescription'
        }
        /// <summary>
        /// Test the property 'LastName'
        /// </summary>
        [Fact]
        public void LastNameTest()
        {
            // TODO unit test for the property 'LastName'
        }
        /// <summary>
        /// Test the property 'MobilePhoneNumber'
        /// </summary>
        [Fact]
        public void MobilePhoneNumberTest()
        {
            // TODO unit test for the property 'MobilePhoneNumber'
        }
        /// <summary>
        /// Test the property 'MotherMaidenName'
        /// </summary>
        [Fact]
        public void MotherMaidenNameTest()
        {
            // TODO unit test for the property 'MotherMaidenName'
        }
        /// <summary>
        /// Test the property 'NationalIdentifier'
        /// </summary>
        [Fact]
        public void NationalIdentifierTest()
        {
            // TODO unit test for the property 'NationalIdentifier'
        }
        /// <summary>
        /// Test the property 'UserId'
        /// </summary>
        [Fact]
        public void UserIdTest()
        {
            // TODO unit test for the property 'UserId'
        }
        /// <summary>
        /// Test the property 'UserIdType'
        /// </summary>
        [Fact]
        public void UserIdTypeTest()
        {
            // TODO unit test for the property 'UserIdType'
        }
        /// <summary>
        /// Test the property 'Vip'
        /// </summary>
        [Fact]
        public void VipTest()
        {
            // TODO unit test for the property 'Vip'
        }
        /// <summary>
        /// Test the property 'UserDefined1'
        /// </summary>
        [Fact]
        public void UserDefined1Test()
        {
            // TODO unit test for the property 'UserDefined1'
        }

    }

}
