/*
 * Pay with Rewards APIs
 *
 * Pay with Rewards allows cardholders to redeem points for purchases made with an enrolled Mastercard card. The following APIs create the Pay with Rewards user experience, and can be used inside a banking app or other mobile apps.
 *
 * The version of the OpenAPI document: 1.1
 * Contact: paywithrewards@mastercard.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Pbo.App.MastercardApi.Client.Api;
using Pbo.App.MastercardApi.Client.Model;
using Pbo.App.MastercardApi.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Pbo.App.MastercardApi.Client.Test.Model
{
    /// <summary>
    ///  Class for testing UserEnrollResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UserEnrollResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UserEnrollResponse
        //private UserEnrollResponse instance;

        public UserEnrollResponseTests()
        {
            // TODO uncomment below to create an instance of UserEnrollResponse
            //instance = new UserEnrollResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UserEnrollResponse
        /// </summary>
        [Fact]
        public void UserEnrollResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" UserEnrollResponse
            //Assert.IsType<UserEnrollResponse>(instance);
        }


        /// <summary>
        /// Test the property 'UserId'
        /// </summary>
        [Fact]
        public void UserIdTest()
        {
            // TODO unit test for the property 'UserId'
        }
        /// <summary>
        /// Test the property 'UserIdType'
        /// </summary>
        [Fact]
        public void UserIdTypeTest()
        {
            // TODO unit test for the property 'UserIdType'
        }
        /// <summary>
        /// Test the property 'AccountId'
        /// </summary>
        [Fact]
        public void AccountIdTest()
        {
            // TODO unit test for the property 'AccountId'
        }
        /// <summary>
        /// Test the property 'AccountIdType'
        /// </summary>
        [Fact]
        public void AccountIdTypeTest()
        {
            // TODO unit test for the property 'AccountIdType'
        }

    }

}
